### ISSUE TITLE
[BUG] Enable 0.25 not possible

### ISSUE THREAD

**Issue by abergmeier** [hlorus/CAD_Sketcher#245] opened 2022-08-10 18:27 UTC
### Contact Details

abergmeier@gmx.net

### Description

Added 0.25 from zip but cannot be activated.

Seems to die in `icon_manager.py:73`.

### Addon Version

0.25.0

### Blender Version

3.2.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment] 2022-08-10 20:01
Could you post a screenshot of the console?

**Comment by ra100** [comment] 2022-08-20 17:59
Seems that the "icons" folder can't be found, I've copied all folders from `ressources` one level higher, and addon could be enabled without the error.

**Comment by hlorus** [comment] 2022-08-21 07:11
The zip seems to be correct, at least theres a folder with icons in that directory. Maybe try completely removing the addon folder and adding it back from the zip. There could be some strange stuff going on when it's just overwritten e.g. old files laying around.

**Comment by ra100** [comment] 2022-08-21 07:29
I'm not sure what's wrong, but when I download the zip from here: https://github.com/hlorus/CAD-Sketcher/archive/refs/heads/main.zip, I get this content:

![image](https://user-images.githubusercontent.com/3185410/185780333-a9c8a859-d9ff-45cd-8f9f-afd0312553c2.png)

and icons_manager has the proper link `filepath = Path(Path(__file__).parent, "ressources/icons")` in there

I've been trying to remove addon and then install back, didn't work. But now, I've tried to remove addon from older config version of blender, downloaded zip again, and seems working.
It looks weird why it didn't work before. Anyway, my issue is solved.

**Comment by calebmeyer** [comment] 2022-11-04 00:58
@ra100's fix worked for me as well. Clicking the checkbox to enable the addon was giving this error:
![image](https://user-images.githubusercontent.com/3342777/199862552-82924dc7-2c39-41d5-b9be-bc6bf71acc90.png)

And copying icons up fixes it.

**Comment by Cheaterman** [comment] 2023-02-24 18:41
This was most certainly fixed by #337 - please re-open in case you can reproduce it with current CAD Sketcher. As @ra100 noted, it's probably a good idea to entirely remove your CAD Sketcher addon folder before reinstalling.

**Closed by Cheaterman** 2023-02-24 18:41 UTC
Labels: bug
