### ISSUE TITLE
[REQUEST] Use the 'Shift-Click to multiselect' UX pattern

### ISSUE THREAD

**Issue by Hyperlooper** [hlorus/CAD_Sketcher#43] opened 2022-04-27 00:38 UTC
Blender uses the Shift-Click to paradigm to select multiple objects. By default, click-selecting an object in Blender will un-select the previous selection unless Shift is used.

When editing a Sketch in CAD Sketcher, the behavior seems different: Sketch entities remain selected once clicked regardless of if Shift is held or not, and they remain selected until they are clicked on again. 

It might be more intuitive to use the same UX pattern used elsewhere in Blender, and would have the added benefit of being slightly less click-intensive. The current behavior requires that a user click each entity at least twice: once to select it, and then later on it must be clicked again to un-select it.

**Comment by hlorus** [comment] 2022-04-27 05:34
Note you can quickly deselect all entities by pressing ESC in the select tool or clicking empty space.

That being said this is mostly a duplicate of #40 so i'm gonna close it. Thanks anyway for the proposal.

**Closed** 2022-04-27 05:34 UTC
Labels: feature request
