### ISSUE TITLE
[BUG] Reversed normals

### ISSUE THREAD

**Issue by chiboreache** [hlorus/CAD_Sketcher#313] opened 2022-11-23 06:32 UTC
### Description

`c+N` helps, but after edit sketch it's reverse it again

![2022-11-23x09:28:03](https://user-images.githubusercontent.com/16459251/203484799-8d9248e5-bbbc-4759-acd8-68bfcc8995fe.jpg)

### Addon Version

0.25.0

### Blender Version

3.3.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment] 2023-01-17 08:25
I'm assuming that the "Flip Normals" option of the solidify modifier should do the trick...?

**Comment by hlorus** [comment] 2023-01-23 17:30
Closing as duplicate of #317

**Closed** 2023-01-23 17:30 UTC
Labels: bug
