### ISSUE TITLE
[BUG]Error on install v0.27.1

### ISSUE THREAD

**Issue by jikometrix** [hlorus/CAD_Sketcher#382] opened 2023-05-02 20:55 UTC
### Contact Details

mbrando@jikometrix.net

### Description

I tried to install v0.27.1 cad sketcher on Blender 3.5.1 on Mac M1 with os 13.3.1
I get the attached error. 
<img width="1289" alt="Screenshot 2023-05-02 at 3 53 08 PM" src="https://user-images.githubusercontent.com/56171052/235783906-fb421b34-17b0-4184-911e-8f88474adc7a.png">
<img width="1143" alt="Screenshot 2023-05-02 at 3 53 15 PM" src="https://user-images.githubusercontent.com/56171052/235783912-c140141c-cf4d-4e0a-8a3f-c071181fda95.png">

### Addon Version

0.27.1

### Blender Version

3.5.1

### What platform are you running on?

Mac OSX

**Comment by Benjemen69** [comment] 2023-05-03 03:24
Same issue here. Tried downloading and installing, the issue still persists.

**Comment by hlorus** [comment] 2023-05-03 07:36
Closing as duplicate of #375

**Closed** 2023-05-03 07:36 UTC
Labels: bug
