### ISSUE TITLE
[BUG] cannot create sketch, no workplane appears

### ISSUE THREAD

**Issue by mifamac** [hlorus/CAD_Sketcher#407] opened 2023-07-26 16:50 UTC
### Contact Details

mifamac@macnews.de

### Description

If I click on "Add sketcher" there appers no workplane to select.

Installation was succesful, solver registered.

### Addon Version

0.27.2

### Blender Version

3.60

### What platform are you running on?

Mac OSX

**Comment by aqeelahmed168** [comment] 2023-07-30 09:21
I encountered similar problem with Blender 3.6.1.

**Comment by katistix** [comment] 2023-07-31 13:26
+1, me too, same problem on 3.6.1

**Comment by hlorus** [comment] 2023-07-31 13:42
Duplicate of #375

**Closed** 2023-07-31 13:42 UTC
Labels: bug

**Comment by CFTechnology** [comment] 2023-08-28 03:08
<img width="657" alt="image" src="https://github.com/hlorus/CAD_Sketcher/assets/13896726/f8f6101d-0bf2-4a5a-94f6-c5ffd5ff3ef3">
