### ISSUE TITLE
[BUG] Intersecting bevels causing Blender to crash

### ISSUE THREAD

**Issue by branlam** [hlorus/CAD_Sketcher#302] opened 2022-10-18 21:54 UTC
### Description

When using the bevel on a point in CAD Sketcher, if you set a radius high enough where the second bevel may cut into the first bevel, it will cause it to crash blender.

<img width="317" alt="Screenshot 2022-10-18 144607" src="https://user-images.githubusercontent.com/35716436/196551682-6491183a-4427-4bcf-aa97-249ff63bbcf8.png">

The image above, I tried to set the bevel radius to 10 on the top and bottom points. Setting the top bevel to a radius of 10 after setting the bottom one to 10 would always crash my blender.

### Addon Version

0.25

### Blender Version

3.31

### What platform are you running on?

Windows

**Comment by hlorus** [comment] 2022-10-19 11:43
Thanks for the Report, i cannot reproduce this both on windows and linux. Does it also happen when there are no constraints?

**Comment by branlam** [comment] 2022-10-19 18:09
I tried it once again by simply making a small rectangle and setting the radius to 2. It crashed on me again from a fresh blender with only those steps. Is there other details I can provide that might help with explaining this issue for me?

**Comment by hlorus** [comment] 2022-10-20 07:10
Still cannot reproduce... a screen recording might be helpful. Also you might try to completely remove the addon and install the newest version.

**Comment by branlam** [comment] 2022-10-20 18:59
I was already on the newest version 0.25.0. But I did uninstall the addon and installed it again just to make sure.

Here is a screen capture of a fresh install of the addon and it causing blender to crash

https://user-images.githubusercontent.com/35716436/197034437-df67d355-5d39-4d7e-9ad3-e4f5f6487802.mp4

**Comment by hlorus** [comment] 2022-10-20 19:53
Sorry, i wasn't clear. This is likely resolved in the latest development version that you can get from GitHub directly. That version will soonish be pushed to gumroad along with some update notes.

**Comment by branlam** [comment] 2022-10-20 21:01
Ohh I see. I have downloaded the version from GitHub directly, the issue does not appear with that version 👍. Thank you very much

**Closed** 2022-10-21 05:42 UTC
Labels: bug
