### ISSUE TITLE
[BUG] Sketch Workplane does not follow the constructed Blender Object

### ISSUE THREAD

**Issue by hariedo** [hlorus/CAD_Sketcher#135] opened 2022-05-21 16:06 UTC
### Description

Original Sketch Workplane does not follow constructed Blender Object, and forces Blender Object to align with Sketch Workplane.

1: create a sketch on any workplane, e.g., XY plane
2: create some sketch elements and constraints
3: set conversion to mesh
4: exit sketch to see mesh

5: grab or rotate resulting mesh Blender Object, say, to orient this new part with other parts of an assembly

6: enter the sketch that created this mesh
7: exit the sketch to see the mesh it creates

Upon 6, the Blender Object disappears as expected, but the Sketch appears where it was originally created.

Upon 7, the Blender Object reappears as expected, but the Blender Object is oriented and positioned at the Sketch Workplane position, not its desired assembly home.

When creating a new Sketch, the Sketch Workplane should be relative to the world, e.g, at the world origin, but once the sketch is converted, the Sketch Workplane should be maintained relative to the hosting Blender Object's origin and orientation.  Entering and exiting the Sketch should let you see and revise the sketch in situ, and the Blender Object's location and orientation should not change.

There are some other aspects of this when choosing to create workplanes relative to existing geometry, which will need to be addressed consistently as well.  I expect that it will be consistent if you replace "Blender Object's origin" above with "Blender Object's _local_ origin" and appropriately set Blender parentage when creating workplanes relative to existing geometry.

### Addon Version

0.22.6

### Blender Version

3.0

### What platform are you running on?

Mac OSX

**Comment by amrsoll** [comment] 2022-10-07 12:31
I agree with @theoryshaw .

As far as I can tell, it is a duplicate of #10

Feel free to reopen if you can explain whether that workaround doesn't work for you.

**Closed** 2022-10-07 12:31 UTC
Labels: bug
