### ISSUE TITLE
Can't activate on Blender 3.5 MacOS (ventura)

### ISSUE THREAD

**Issue by jeanmartin13** [hlorus/CAD_Sketcher#375] opened 2023-03-30 17:18 UTC
Error message when activating on Blender 3.5 on MacOS Ventura. CadSketcher v0.27.1. 

`Traceback (most recent call last):
  File "/Applications/Blender 3.5.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/jean-martin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/__init__.py", line 3, in <module>
    from . import icon_manager, global_data
  File "/Users/jean-martin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/icon_manager.py", line 13, in <module>
    _icon_shader = Shaders.uniform_color_image_2d()
  File "/Users/jean-martin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/shaders.py", line 93, in uniform_color_image_2d
    return GPUShader(
Exception: Shader Compile Error, see console for more details

`

Maybe openGL/Metal issue ?

**Comment by hlorus** [comment] 2023-03-30 17:57
Thanks for the report.

> Exception: Shader Compile Error, see console for more details

Would be great to get these details. To get the console output see here: https://hlorus.github.io/CAD_Sketcher/advanced/#console-output

Also tagging @Cheaterman here as he wrote that shader.

**Comment by jeanmartin13** [comment] 2023-03-31 10:01
@Cheaterman @hlorus 

Thanks for the answer? I hope I did the right procedure. I didn't find any log in 

`/Users/jean-martin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main`

Here is the console output :

`jean-martin@Mac-Pro ~ % /Applications/Blender\ 3.5.app/Contents/MacOS/Blender 
Read prefs: /Users/jean-martin/Library/Application Support/Blender/3.5/config/userpref.blend
Device with name AMD Radeon RX 6800 XT supports metal minimum requirements
METAL API - DETECTED GPU: AMD Radeon RX 6800 XT
Got asset list in: 0.000s
WARN (bgl): source/blender/python/generic/bgl.c:2656 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
register
HardOps 0.9.87.35 available!
Registered MACHIN3tools 1.3.0 with 1 tool, 1 pie menu
Traceback (most recent call last):
  File "/Applications/Blender 3.5.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/jean-martin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/__init__.py", line 3, in <module>
    from . import icon_manager, global_data
  File "/Users/jean-martin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/icon_manager.py", line 13, in <module>
    _icon_shader = Shaders.uniform_color_image_2d()
  File "/Users/jean-martin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/shaders.py", line 93, in uniform_color_image_2d
    return GPUShader(
Exception: Shader Compile Error, see console for more details

Saved session recovery to '/var/folders/0x/rm2v1zwn74l3xngb3wvsqj9w0000gn/T/quit.blend'
Writing userprefs: '/Users/jean-martin/Library/Application Support/Blender/3.5/config/userpref.blend' ok
Info: Preferences saved
unregister
Warning keymap '3D View Tool: Hops' not found in 'Blender'!
Warning keymap '3D View Tool: Hops' not found in 'Blender addon'!
Unregistered MACHIN3tools 1.3.0.

Blender quit
jean-martin@Mac-Pro ~ % 
`

**Comment by hlorus** [comment] 2023-03-31 13:06
> WARN (bgl): source/blender/python/generic/bgl.c:2656 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.

Looks like you have another addon enabled that still uses the bgl module. Not sure if that might be problematic. Would be great to test if it still happens when all other addons are disabled.

**Comment by jeanmartin13** [comment] 2023-03-31 13:14
I still have the issue with only those addons activated. I think that those are the default activated addons.

![Capture d’écran 2023-03-31 à 15 13 09](https://user-images.githubusercontent.com/93234385/229129651-35bf7795-ea5b-4fb9-8a4e-ae731530af34.png)

**Comment by hlorus** [comment] 2023-03-31 13:56
Hmm strange!
Did you try both gpu backends? https://code.blender.org/2023/01/introducing-the-blender-metal-viewport/

**Comment by ucanf1yhi** [comment] 2023-03-31 19:04
OpenGL is working but Metal have error.

**Comment by jeanmartin13** [comment] 2023-04-02 08:54
> Hmm strange! Did you try both gpu backends? https://code.blender.org/2023/01/introducing-the-blender-metal-viewport/

Yes, it works fine with openGL backend. Do that mean  metal backend has to be improved or that the addon needs adaptation to metal backend ?

**Comment by Fran6nd** [comment] 2023-04-08 14:00
I have just read all the thread and I am facing exactly the same issue. On an M1 Mac VENTURA

**Comment by hlorus** [comment] 2023-04-08 19:27
The addon has switched to the gpu module quite a while back, it seems like the metal backend doesn't support all custom shaders but i assume this will be addressed soon by blender.

**Comment by JackNeto** [comment] 2023-04-17 14:00
I just did a fresh installation of Blender 3.5.0 on an M2 Mac Ventura and had the same problem. Changing Edit>Preferences>System>GPU Backend to `OpenGL` fixed it for me.

**Comment by hyperswine** [comment] 2023-04-19 07:31
the addon can be enabled when I switch to opengl, but pressing `ctrl` + `shift` + `a` and going into sketch mode doesnt work for me. The planes show up but I cant go into sketch mode from it. I get an exception if I click on anything else

**Comment by rafo** [comment] 2023-04-25 12:21
> I just did a fresh installation of Blender 3.5.0 on an M2 Mac Ventura and had the same problem. Changing Edit>Preferences>System>GPU Backend to `OpenGL` fixed it for me.

Can confirm for M1 Ventura 13.1.

**Comment by BKLronin** [comment] 2023-05-13 11:14
Working fine here on M1 and Ventura latest. I dont have an option to switch to opengl in system settings. So must be metal?

**Comment by DiederikvandenB** [comment] 2023-05-14 15:08
Same issue. Switching to OpenGL for the time works.

Coming from an MBA M2. It runs fine on my Studio M1 Max though 👀

**Comment by sammcj** [comment] 2023-05-22 00:17
Likewise, spent ages trying to figure out what was up until I find this issue! If it's not metal compatible it might be worth calling out in the readme perhaps.

**Comment by hlorus** [comment] 2023-06-07 14:50
Could someone test if it works with the newest version?

Commit: https://github.com/hlorus/CAD_Sketcher/commit/0f2bb9ba559fb760b484c013032b02cf99d0d9df

**Comment by hlorus** [comment] 2023-06-07 20:51
> I can install it and it shows up in toolbar but I cant create a sketch un latest ventura on M1 with Blender 3.5.x
> 
> ```
> Python: Traceback (most recent call last):
>   File "/Users/bklronin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/gizmos/preselection.py", line 51, in test_select
>     ensure_selection_texture(context)
>   File "/Users/bklronin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/draw_handler.py", line 43, in ensure_selection_texture
>     draw_selection_buffer(context)
>   File "/Users/bklronin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/draw_handler.py", line 36, in draw_selection_buffer
>     e.draw_id(context)
>   File "/Users/bklronin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/model/base_entity.py", line 252, in draw_id
>     shader = self._id_shader
>   File "/Users/bklronin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/model/base_entity.py", line 73, in _id_shader
>     return Shaders.id_shader_3d()
>   File "/Users/bklronin/Library/Application Support/Blender/3.5/scripts/addons/CAD_Sketcher-main/shaders.py", line 217, in id_shader_3d
>     return GPUShader(vertex_shader, fragment_shader)
> Exception: Shader Compile Error, see console for more details
> ```
> 

Does it work with opengl? It looks like it wasn't just a problem during startup unfortunately...

**Comment by BKLronin** [comment] 2023-06-07 20:57
Yes it does but no sketch can be created in metal mode.

**Comment by claytonbp** [comment] 2023-06-10 18:04
I can also confirm that there is no sketch in metal mode for an intel based iMac

**Comment by StarWitch** [comment] 2023-07-01 19:26
Same issue here using an Intel Mac with Blender 3.6 and macOS Ventura 13.4.1.

**Comment by katistix** [comment] 2023-07-31 14:04
Now the sketch planes are visible, but i can only tap on the edges, and after i click on them, they disappear

https://github.com/hlorus/CAD_Sketcher/assets/45326403/46b8e5d7-c0ab-4769-b01a-689a721025b2

**Comment by hlorus** [comment] 2023-08-01 09:16
> Everything works as expected except for the width of the lines that seems to be solved at #29 

Exactly, that's actually an expected regression. The problem is that metal doesn't support geometry shaders and therefore the custom line width shader cannot be used here.

As the addon's selection system usually relies on shaders it's important to be able to draw thick lines. To shortcut this problem i've made another change in this branch so that geometry is still easily selectable even with super thin geometry.
I'm quite surprised how thin the default line width is tho...

**Comment by StarWitch** [comment] 2023-09-30 22:08
Confirming that this patch makes the plugin usable on macOS using Metal. It still doesn't look exactly right due to line width but it's functional now.

**Comment by hlorus** [comment] 2023-11-15 06:47
The mentioned branch has now been merged so the issue should be resolved.

**Closed by hlorus** 2023-11-15 06:47 UTC
