### ISSUE TITLE
Feature Request: Copy & Paste sketch entities

### ISSUE THREAD

**Issue by Shaddy-ElDesouky** [hlorus/CAD_Sketcher#273] opened 2022-08-26 17:01 UTC
**Motivation / Existing Problem**
After selecting multiple entities in the sketch I couldn't copy them to paste them in another place inside the same sketch.

**Description**
For faster drawing, I need to select multiple entities and copy and paste them in the same sketch 

**Alternative Solutions**

**Mockup**

**Comment by hlorus** [comment] 2022-11-19 14:51
Duplicate of #255

**Closed by hlorus** 2022-11-19 14:51 UTC
